version: '2'

services:

  app:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/minodisk/go-learn-dbr

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
